### PR TITLE
Platform/projectspage

### LINKED ISSUE #10: Update Project Page content under tabs
There are now tabs displayed on a project page. Move content inside these tabs and remove all content outside. This includes the following:

- [x] Greenspaces
- [x] Members
- [x] Orders
- [ ] Settings

### PR DESCRIPTION
**Pull request by grooleivsgard**
## Summary
There's now relevant content added inside the tabs on the Project pages. This still needs to be adjusted and data needs to be mapped correctly, but the major changes are finished. 

Social Media logins are also removed on login page.

## Preview

bilde

## Linked issues

Closes #10 and #18 

## Correct PR Checklist

- [x] I have linked an issue (use e.g. `closes #1`)
- [x] I have assigned Reviewers
- [x] I have assigned an Description label
- [ ] I have assigned a Milestone (if applicable)

### CODE REVIEW

**Comment by kmaciejewska** [comment]
Seems like you can only click on the title/name of the given article - is that 100% intuitive? Seems a bit weird to me but again I'm not an expert on UX 😄

**Comment by grooleivsgard** [comment]
> Seems like you can only click on the title/name of the given article - is that 100% intuitive? Seems a bit weird to me but again I'm not an expert on UX 😄

Agreed, I've fixed it now and will create a new pull request…

**Comment by kmaciejewska** [comment]
> > Seems like you can only click on the title/name of the given article - is that 100% intuitive? Seems a bit weird to me but again I'm not an expert on UX 😄
> 
> Agreed, I've fixed it now :))

LGTM 👍 
I do have a small issue with the image: 

image

It's bigger than the others so automatically card becomes uneven with respect to others. The best would be to either resize this one according to the properties of that tomato image for example, or, looking at the images we have come up with a reasonable height/width. However, I think the size of the tomato card and the others looks like the most suitable choice

**Comment by grooleivsgard** [comment]
> > > Seems like you can only click on the title/name of the given article - is that 100% intuitive? Seems a bit weird to me but again I'm not an expert on UX 😄
> > 
> > 
> > Agreed, I've fixed it now :))
> 
> LGTM 👍 I do have a small issue with the image:
> 
> image
> 
> It's bigger than the others so automatically the card becomes uneven with respect to others. The best would be to either resize this one according to the properties of that tomato image for example, or, looking at the images we have come up with a reasonable height/width. However, I think the size of the tomato card and the others looks like the most suitable choice

This is a Card component imported from MUI, so I'm not able to overwrite its settings for scaling the images. However, if we crop all images to 524 x 492, they will all look the same. This is now done for the rooftop image in the recent push.

bilde

**Comment by kmaciejewska** [comment]
Great! Resolving and merging now 😄

**Review by kmaciejewska — APPROVED** [review]

**Pull request merged**
