### PR TITLE
Validation

### LINKED ISSUE #17: Add validation to Login/Register forms
## Description
Fields such as email or password need to be validated before they are sent to Cognito for jwt tokens

## Correct issue checklist:

- [x] I have added a detailed description
- [x] I have assigned a Description label (enhancement / bug / etc.)

### PR DESCRIPTION
**Pull request by kmaciejewska**
## Summary

Added validation and correct flow of login/register/forgot password.
Note: this is just the flow and validation, no actual functionality yet

## Linked issues

closes #17 

## Correct PR Checklist

- [x] I have linked an issue (use e.g. `closes #1`)
- [x] I have assigned Reviewers
- [x] I have assigned an Description label
- [x] I have assigned a Milestone (if applicable)

### CODE REVIEW

**Comment by grooleivsgard** [comment]
I don't think there should be this type of validation ("Password must be at least 8 characters/contain numbers/upper cases" etc.) on the login page, only when a user is creating a new password. Other than that, awesome validations :))

bilde

**Comment by grooleivsgard** [comment]
I am not receiving an error when I attempt to login with a wrong password, only with an invalid email. For security reasons, could you make the feedback "Incorrect username or password"?

**Comment by kmaciejewska** [comment]
> I am not receiving an error when I attempt to login with a wrong password, only with an invalid email. For security reasons, could you make the feedback "Incorrect username or password"?

That one is in functionality - on redux branch because it comes from backend :) as i mentioned here this is just a flow, so you don't actually log in. But if you do try to provide wrong credentials the output is as follows: 

image

**Comment by grooleivsgard** [comment]
> 

I am not referencing functionality. When I input the wrong email or password, I'm not receiving the error as shown in the image you attached.

**Review by grooleivsgard — APPROVED** [review]
All looks good :)

**Pull request merged**
