### PR TITLE
Add to project modal

### LINKED ISSUE #27: Add component modal for "Add to Project"
## Description
Create modal component for the "Add to Project" button

## Correct issue checklist:

- [ ] I have added a detailed description
- [ ] I have assigned a Description label (enhancement / bug / etc.)
- [ ] I have assigned a contributor
- [ ] I have added a Milestone (if applicable)

### PR DESCRIPTION
**Pull request by grooleivsgard**
## Summary
I've connected the Add to Project button to a new modal component where the user will choose project and greenspace from dropdowns. These values are not mapped, so it's currently mock data.

## Preview

bilde

## Linked issues

Closes #27 #18 

## Correct PR Checklist

- [x] I have linked an issue (use e.g. `closes #1`)
- [x] I have assigned Reviewers
- [x] I have assigned an Description label
- [ ] I have assigned a Milestone (if applicable)

### CODE REVIEW

**Review by kmaciejewska — CHANGES_REQUESTED** [review]
There is a couple of errors in the console, if you could have a look at that would be great. Other than that, maybe a more descriptive file name would work better? (something other than ProductDetail maybe?)

**Comment by grooleivsgard** [comment]
> There is a couple of errors in the console, if you could have a look at that would be great. Other than that, maybe a more descriptive file name would work better? (something other than ProductDetail maybe?)

I think those errors come from the template and are not related to this modal? 
Could PlantDetail be a better name for the page? Or are you referencing the modal?

**Comment by kmaciejewska** [comment]
> > There is a couple of errors in the console, if you could have a look at that would be great. Other than that, maybe a more descriptive file name would work better? (something other than ProductDetail maybe?)
> 
> I think those errors come from the template and are not related to this modal? Could PlantDetail be a better name for the page? Or are you referencing the modal?

Correct, one of them (about the icon) is indeed present on main which means it's probably from earlier. The other is on this branch tho, so maybe something else that got changed? As for the file, we have multiple products - if we will use the same component that is defined in that ProductDetail.js file then I guess it's okay after all but this file is now prepared for greenspaces/projects/concepts only. It must be more generic and reusable if we want to have it for all of the "products" we offer. But if we will be using different layouts for different products (plants vs concepts) then I suggest having a different name e.g ConceptDetail and PlantDetail. We could also have a modal for plant details but that is up to you 👍

**Comment by grooleivsgard** [comment]
> > > There is a couple of errors in the console, if you could have a look at that would be great. Other than that, maybe a more descriptive file name would work better? (something other than ProductDetail maybe?)
> > 
> > 
> > I think those errors come from the template and are not related to this modal? Could PlantDetail be a better name for the page? Or are you referencing the modal?
> 
> Correct, one of them (about the icon) is indeed present on main which means it's probably from earlier. The other is on this branch tho, so maybe something else that got changed? As for the file, we have multiple products - if we will use the same component that is defined in that ProductDetail.js file then I guess it's okay after all but this file is now prepared for greenspaces/projects/concepts only. It must be more generic and reusable if we want to have it for all of the "products" we offer (check out passing children or other props). But if we will be using different layouts for different products (plants vs concepts) then I suggest having a different name e.g ConceptDetail and PlantDetail. We could also have a modal for plant details but that is up to you 👍

Now the error related to the modal is fixed and the name is changed to ConceptDetail. I will create another issue related to the layouts of ConceptDetail and PlantDetail :)

**Review by kmaciejewska — APPROVED** [review]

**Comment by kmaciejewska** [comment]
Great job Gro 💯

**Pull request merged**
